# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10.20.0


# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

before_script:
  - apt-get install -qq -y curl
  - curl -O -L https://github.com/s3tools/s3cmd/releases/download/v2.1.0/s3cmd-2.1.0.tar.gz
  - tar xzf s3cmd-2.1.0.tar.gz
  - cd s3cmd-2.1.0
  - cp -R s3cmd S3 ~/bin
  - export PATH=$HOME/bin:$PATH
  - . ~/.bash_profile
  - s3cmd

cache:
  paths:
    - node_modules/

build:
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - build/
